[project]
name = "livereduce"
description = "Daemon for running live data reduction with systemd"
version="1.10"
#dynamic = ["version"]
requires-python = ">=3.9"
#dependencies = [
#               "mantidworkbench >= 6.7.20230830",
#    "pyoncat ~= 1.6"
#]                                                                                                                license = { text = "MIT License" }
authors = [{name="Pete Peterson",email="petersonpf@ornl.gov"}]

[project.urls]
Homepage = "https://github.com/mantidproject/livereduce"
